# Changes here will be overwritten by Copier
_commit: 0.11.0
_src_path: https://github.com/pawamoy/copier-pdm.git
author_email: pawamoy@pm.me
author_fullname: Timothée Mazzucotelli
author_username: pawamoy
copyright_date: '2020'
copyright_holder: Timothée Mazzucotelli
copyright_holder_email: pawamoy@pm.me
copyright_license: ISC License
project_description: A simple task runner.
project_name: Duty
python_package_command_line_name: duty
python_package_distribution_name: duty
python_package_import_name: duty
repository_name: duty
repository_namespace: pawamoy
repository_provider: github.com
use_precommit: false

