site_name: "Duty"
site_description: "A simple task runner."
site_url: "https://pawamoy.github.io/duty"
repo_url: "https://github.com/pawamoy/duty"
repo_name: "pawamoy/duty"

nav:
- Home:
  - Overview: index.md
  - Changelog: changelog.md
  - Credits: credits.md
- Usage: usage.md
- Code Reference:
  - cli.py: reference/cli.md
  - collection.py: reference/collection.md
  - context.py: reference/context.md
  - decorator.py: reference/decorator.md
  - exceptions.py: reference/exceptions.md
  - validation.py: reference/validation.md
- Development:
  - Contributing: contributing.md
  - Code of Conduct: code_of_conduct.md
  - Coverage report: coverage.md

theme:
  name: material
  features:
  - navigation.tabs
  palette:
    scheme: slate
    primary: teal
    accent: purple

extra_css:
- css/mkdocstrings.css

markdown_extensions:
- admonition
- markdown_include.include
- pymdownx.emoji
- pymdownx.magiclink
- pymdownx.superfences
- pymdownx.tabbed
- pymdownx.tasklist
- toc:
    permalink: "¤"

plugins:
- search
- coverage:
    html_report_dir: build/coverage
- mkdocstrings:
    watch:
    - src/duty
    - build/coverage
